
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Nov 20 21:09:37 COT 2025
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import java.util.*;
import ast.*;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Thu Nov 20 21:09:37 COT 2025
  */
public class ProManParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ProManParser() {super();}

  /** Constructor which sets the default scanner. */
  public ProManParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ProManParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\002\004\000\002\002\021\000\002\003" +
    "\015\000\002\004\013\000\002\005\007\000\002\006\010" +
    "\000\002\016\005\000\002\016\004\000\002\007\007\000" +
    "\002\017\005\000\002\017\004\000\002\020\005\000\002" +
    "\020\004\000\002\010\006\000\002\021\011\000\002\021" +
    "\010\000\002\011\006\000\002\022\006\000\002\022\005" +
    "\000\002\012\006\000\002\023\011\000\002\023\010\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\013\010\000\002\024\007\000\002\024\006\000\002\014" +
    "\013\000\002\015\010\000\002\025\006\000\002\025\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\222\000\004\004\004\001\002\000\004\060\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\056\010\001\002\000\004\005\011\001\002\000" +
    "\004\056\213\001\002\000\004\006\014\001\002\000\004" +
    "\007\026\001\002\000\004\056\015\001\002\000\004\024" +
    "\016\001\002\000\004\060\017\001\002\000\004\025\020" +
    "\001\002\000\004\060\021\001\002\000\004\026\022\001" +
    "\002\000\004\060\023\001\002\000\004\057\024\001\002" +
    "\000\004\007\ufffe\001\002\000\004\010\034\001\002\000" +
    "\004\056\027\001\002\000\004\027\030\001\002\000\004" +
    "\060\031\001\002\000\004\057\032\001\002\000\004\010" +
    "\ufffd\001\002\000\004\011\047\001\002\000\004\056\035" +
    "\001\002\000\004\030\036\001\002\000\004\060\037\001" +
    "\002\000\004\031\041\001\002\000\006\031\044\057\043" +
    "\001\002\000\004\060\042\001\002\000\006\031\ufffa\057" +
    "\ufffa\001\002\000\004\011\ufffc\001\002\000\004\060\045" +
    "\001\002\000\006\031\ufffb\057\ufffb\001\002\000\004\012" +
    "\064\001\002\000\004\056\050\001\002\000\004\032\052" +
    "\001\002\000\006\032\054\033\055\001\002\000\004\060" +
    "\053\001\002\000\006\032\ufff7\033\ufff7\001\002\000\004" +
    "\060\063\001\002\000\004\060\062\001\002\000\006\033" +
    "\060\057\057\001\002\000\004\012\ufff9\001\002\000\004" +
    "\060\061\001\002\000\006\033\ufff6\057\ufff6\001\002\000" +
    "\006\033\ufff5\057\ufff5\001\002\000\006\032\ufff8\033\ufff8" +
    "\001\002\000\004\056\174\001\002\000\004\013\067\001" +
    "\002\000\004\014\102\001\002\000\004\056\070\001\002" +
    "\000\004\037\072\001\002\000\006\037\075\057\076\001" +
    "\002\000\004\060\073\001\002\000\004\060\074\001\002" +
    "\000\006\037\uffef\057\uffef\001\002\000\004\060\077\001" +
    "\002\000\004\014\ufff1\001\002\000\004\060\100\001\002" +
    "\000\006\037\ufff0\057\ufff0\001\002\000\004\015\126\001" +
    "\002\000\004\056\103\001\002\000\004\040\104\001\002" +
    "\000\004\060\120\001\002\000\006\040\106\057\107\001" +
    "\002\000\004\060\110\001\002\000\004\015\uffee\001\002" +
    "\000\004\041\111\001\002\000\010\042\113\043\114\044" +
    "\115\001\002\000\004\045\116\001\002\000\004\045\uffeb" +
    "\001\002\000\004\045\uffea\001\002\000\004\045\uffe9\001" +
    "\002\000\004\060\117\001\002\000\006\040\uffed\057\uffed" +
    "\001\002\000\004\041\121\001\002\000\010\042\113\043" +
    "\114\044\115\001\002\000\004\045\123\001\002\000\004" +
    "\060\124\001\002\000\006\040\uffec\057\uffec\001\002\000" +
    "\004\016\144\001\002\000\004\056\127\001\002\000\004" +
    "\046\130\001\002\000\004\060\131\001\002\000\004\047" +
    "\132\001\002\000\004\060\141\001\002\000\006\047\134" +
    "\057\135\001\002\000\004\060\136\001\002\000\004\016" +
    "\uffe8\001\002\000\004\050\137\001\002\000\004\061\140" +
    "\001\002\000\006\047\uffe7\057\uffe7\001\002\000\004\050" +
    "\142\001\002\000\004\061\143\001\002\000\006\047\uffe6" +
    "\057\uffe6\001\002\000\004\056\164\001\002\000\004\017" +
    "\147\001\002\000\004\057\163\001\002\000\004\056\150" +
    "\001\002\000\004\054\151\001\002\000\004\060\152\001" +
    "\002\000\004\055\153\001\002\000\004\060\161\001\002" +
    "\000\006\055\155\057\156\001\002\000\004\060\157\001" +
    "\002\000\004\057\uffe4\001\002\000\004\060\160\001\002" +
    "\000\006\055\uffe3\057\uffe3\001\002\000\004\060\162\001" +
    "\002\000\006\055\uffe2\057\uffe2\001\002\000\004\002\000" +
    "\001\002\000\004\051\165\001\002\000\004\060\166\001" +
    "\002\000\004\052\167\001\002\000\004\060\170\001\002" +
    "\000\004\053\171\001\002\000\004\060\172\001\002\000" +
    "\004\057\173\001\002\000\004\017\uffe5\001\002\000\004" +
    "\034\175\001\002\000\004\060\206\001\002\000\006\034" +
    "\177\057\200\001\002\000\004\060\201\001\002\000\004" +
    "\013\ufff4\001\002\000\004\035\202\001\002\000\004\060" +
    "\203\001\002\000\004\036\204\001\002\000\004\060\205" +
    "\001\002\000\006\034\ufff3\057\ufff3\001\002\000\004\035" +
    "\207\001\002\000\004\060\210\001\002\000\004\036\211" +
    "\001\002\000\004\060\212\001\002\000\006\034\ufff2\057" +
    "\ufff2\001\002\000\004\020\214\001\002\000\004\060\215" +
    "\001\002\000\004\021\216\001\002\000\004\060\217\001" +
    "\002\000\004\022\220\001\002\000\004\060\221\001\002" +
    "\000\004\023\222\001\002\000\004\060\223\001\002\000" +
    "\004\057\224\001\002\000\004\006\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\222\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\011\001\001\000\002\001\001\000\004\004\012\001" +
    "\001\000\004\005\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\032\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\016\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\064\001\001\000\002\001\001\000\004\017" +
    "\050\001\001\000\004\020\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\065\001\001\000\004\012\100\001\001" +
    "\000\002\001\001\000\004\022\070\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\124\001\001\000\002\001\001" +
    "\000\004\023\104\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\026\111\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\026\121\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\144\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\024\132\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\015\145\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\025\153\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\021\175\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ProManParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ProManParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ProManParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ProManParser$actions {
  private final ProManParser parser;

  /** Constructor */
  CUP$ProManParser$actions(ProManParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ProManParser$do_action_part00000000(
    int                        CUP$ProManParser$act_num,
    java_cup.runtime.lr_parser CUP$ProManParser$parser,
    java.util.Stack            CUP$ProManParser$stack,
    int                        CUP$ProManParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ProManParser$result;

      /* select the action based on the action number */
      switch (CUP$ProManParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= project EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ProjectNode start_val = (ProjectNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		RESULT = start_val;
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ProManParser$parser.done_parsing();
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // project ::= PROJECT STRING LBRACE metadata client context objectives scope schedule team risks budget status approvals RBRACE 
            {
              ProjectNode RESULT =null;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-13)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-13)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-13)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-11)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-11)).right;
		MetadataNode m = (MetadataNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-11)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-10)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-10)).right;
		ClientNode c = (ClientNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-10)).value;
		int ctxleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-9)).left;
		int ctxright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-9)).right;
		ContextNode ctx = (ContextNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-9)).value;
		int objleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-8)).left;
		int objright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-8)).right;
		ObjectivesNode obj = (ObjectivesNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-8)).value;
		int scpleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-7)).left;
		int scpright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-7)).right;
		ScopeNode scp = (ScopeNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-7)).value;
		int schleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).left;
		int schright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).right;
		ScheduleNode sch = (ScheduleNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).right;
		TeamNode t = (TeamNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).right;
		RisksNode r = (RisksNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).right;
		BudgetNode b = (BudgetNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int stright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		StatusNode st = (StatusNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int apleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int apright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ApprovalsNode ap = (ApprovalsNode)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
       RESULT = new ProjectNode(
         pname, // nombre del proyecto
         m,     // metadata
         c,     // client
         ctx,   // context
         obj,   // objectives
         scp,   // scope
         sch,   // schedule
         t,     // team
         r,     // risks
         b,     // budget
         st,    // status
         ap     // approvals
       );
     
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("project",0, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-14)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // metadata ::= METADATA LBRACE CODE STRING VERSION STRING CREATED_ON STRING PREPARED_BY STRING RBRACE 
            {
              MetadataNode RESULT =null;
		int codeleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-7)).left;
		int coderight = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-7)).right;
		String code = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-7)).value;
		int versionleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).left;
		int versionright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).right;
		String version = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).value;
		int createdleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).left;
		int createdright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).right;
		String created = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).value;
		int preparedleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int preparedright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String prepared = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new MetadataNode(
        code,
        version,
        created,
        prepared
      );
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("metadata",1, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-10)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // client ::= CLIENT LBRACE NAME STRING CONTACT STRING EMAIL STRING RBRACE 
            {
              ClientNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).value;
		int contactleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).left;
		int contactright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).right;
		String contact = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).value;
		int emailleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int emailright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String email = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new ClientNode(
        name,
        contact,
        email
      );
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("client",2, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-8)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // context ::= CONTEXT LBRACE SUMMARY STRING RBRACE 
            {
              ContextNode RESULT =null;
		int summaryleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int summaryright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String summary = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new ContextNode(summary);
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("context",3, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // objectives ::= OBJECTIVES LBRACE GENERAL STRING specific_list RBRACE 
            {
              ObjectivesNode RESULT =null;
		int generalleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int generalright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String general = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int specsleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int specsright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<String> specs = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new ObjectivesNode(
        general, // objetivo general
        specs    // lista de específicos
      );
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("objectives",4, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // specific_list ::= specific_list SPECIFIC STRING 
            {
              ArrayList<String> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		ArrayList<String> prev = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      prev.add(s);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("specific_list",12, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // specific_list ::= SPECIFIC STRING 
            {
              ArrayList<String> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<String> list = new ArrayList<>();
      list.add(s);
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("specific_list",12, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // scope ::= SCOPE LBRACE include_list exclude_list RBRACE 
            {
              ScopeNode RESULT =null;
		int incsleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int incsright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		ArrayList<String> incs = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int exsleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int exsright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<String> exs = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new ScopeNode(
        incs,
        exs
      );
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("scope",5, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // include_list ::= include_list INCLUDE STRING 
            {
              ArrayList<String> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		ArrayList<String> prev = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int itemleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String item = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      prev.add(item);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("include_list",13, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // include_list ::= INCLUDE STRING 
            {
              ArrayList<String> RESULT =null;
		int itemleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String item = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<String> list = new ArrayList<>();
      list.add(item);
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("include_list",13, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // exclude_list ::= exclude_list EXCLUDE STRING 
            {
              ArrayList<String> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		ArrayList<String> prev = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int itemleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String item = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      prev.add(item);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("exclude_list",14, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // exclude_list ::= EXCLUDE STRING 
            {
              ArrayList<String> RESULT =null;
		int itemleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String item = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<String> list = new ArrayList<>();
      list.add(item);
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("exclude_list",14, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // schedule ::= SCHEDULE LBRACE phase_list RBRACE 
            {
              ScheduleNode RESULT =null;
		int phasesleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int phasesright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<PhaseNode> phases = (ArrayList<PhaseNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new ScheduleNode(phases);
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("schedule",6, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // phase_list ::= phase_list PHASE STRING START STRING END STRING 
            {
              ArrayList<PhaseNode> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).right;
		ArrayList<PhaseNode> prev = (ArrayList<PhaseNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).value;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).value;
		int startleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int endleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int endright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String end = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      PhaseNode p = new PhaseNode(pname, start, end);
      prev.add(p);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("phase_list",15, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // phase_list ::= PHASE STRING START STRING END STRING 
            {
              ArrayList<PhaseNode> RESULT =null;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).value;
		int startleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int endleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int endright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String end = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<PhaseNode> list = new ArrayList<>();
      list.add(new PhaseNode(pname, start, end));
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("phase_list",15, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // team ::= TEAM LBRACE role_list RBRACE 
            {
              TeamNode RESULT =null;
		int rolesleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int rolesright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<RoleNode> roles = (ArrayList<RoleNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new TeamNode(roles);
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("team",7, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // role_list ::= role_list ROLE STRING STRING 
            {
              ArrayList<RoleNode> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).right;
		ArrayList<RoleNode> prev = (ArrayList<RoleNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).value;
		int roleleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int roleright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String role = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		int personleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int personright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String person = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      RoleNode r = new RoleNode(role, person);
      prev.add(r);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("role_list",16, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // role_list ::= ROLE STRING STRING 
            {
              ArrayList<RoleNode> RESULT =null;
		int roleleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int roleright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String role = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		int personleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int personright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String person = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<RoleNode> list = new ArrayList<>();
      list.add(new RoleNode(role, person));
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("role_list",16, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // risks ::= RISKS LBRACE risk_list RBRACE 
            {
              RisksNode RESULT =null;
		int risks_listleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int risks_listright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<RiskNode> risks_list = (ArrayList<RiskNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new RisksNode(risks_list);
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("risks",8, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // risk_list ::= risk_list RISK STRING LEVEL risk_level MITIGATION STRING 
            {
              ArrayList<RiskNode> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).right;
		ArrayList<RiskNode> prev = (ArrayList<RiskNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)).value;
		int descleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).left;
		int descright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).right;
		String desc = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).value;
		int lvlleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int lvlright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String lvl = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int mitleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int mitright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String mit = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      RiskNode r = new RiskNode(desc, lvl, mit);
      prev.add(r);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("risk_list",17, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-6)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // risk_list ::= RISK STRING LEVEL risk_level MITIGATION STRING 
            {
              ArrayList<RiskNode> RESULT =null;
		int descleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).left;
		int descright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).right;
		String desc = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).value;
		int lvlleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int lvlright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String lvl = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int mitleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int mitright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String mit = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<RiskNode> list = new ArrayList<>();
      list.add(new RiskNode(desc, lvl, mit));
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("risk_list",17, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // risk_level ::= HIGH 
            {
              String RESULT =null;
		 RESULT = "high";   
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("risk_level",20, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // risk_level ::= MEDIUM 
            {
              String RESULT =null;
		 RESULT = "medium"; 
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("risk_level",20, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // risk_level ::= LOW 
            {
              String RESULT =null;
		 RESULT = "low";    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("risk_level",20, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // budget ::= BUDGET LBRACE CURRENCY STRING budget_item_list RBRACE 
            {
              BudgetNode RESULT =null;
		int currencyleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int currencyright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String currency = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int itemsleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int itemsright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<BudgetItemNode> items = (ArrayList<BudgetItemNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new BudgetNode(currency, items);
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("budget",9, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // budget_item_list ::= budget_item_list ITEM STRING COST NUMBER 
            {
              ArrayList<BudgetItemNode> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).right;
		ArrayList<BudgetItemNode> prev = (ArrayList<BudgetItemNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int costleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int costright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		Integer cost = (Integer)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      BudgetItemNode item = new BudgetItemNode(name, cost);
      prev.add(item);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("budget_item_list",18, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-4)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // budget_item_list ::= ITEM STRING COST NUMBER 
            {
              ArrayList<BudgetItemNode> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int costleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int costright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		Integer cost = (Integer)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<BudgetItemNode> list = new ArrayList<>();
      list.add(new BudgetItemNode(name, cost));
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("budget_item_list",18, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // status ::= STATUS LBRACE OVERALL STRING HEALTH STRING COMMENTS STRING RBRACE 
            {
              StatusNode RESULT =null;
		int overallleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).left;
		int overallright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).right;
		String overall = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)).value;
		int healthleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).left;
		int healthright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).right;
		String health = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).value;
		int commentsleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int commentsright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String comments = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new StatusNode(
        overall,
        health,
        comments
      );
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("status",10, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-8)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // approvals ::= APPROVALS LBRACE REQUIRED_BY STRING approver_list RBRACE 
            {
              ApprovalsNode RESULT =null;
		int requiredleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).left;
		int requiredright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).right;
		String required = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)).value;
		int approversleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int approversright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		ArrayList<ApproverNode> approvers = (ArrayList<ApproverNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		
      RESULT = new ApprovalsNode(required, approvers);
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("approvals",11, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-5)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // approver_list ::= approver_list APPROVER STRING STRING 
            {
              ArrayList<ApproverNode> RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).right;
		ArrayList<ApproverNode> prev = (ArrayList<ApproverNode>)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		int roleleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int roleright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String role = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ApproverNode a = new ApproverNode(name, role);
      prev.add(a);
      RESULT = prev;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("approver_list",19, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-3)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // approver_list ::= APPROVER STRING STRING 
            {
              ArrayList<ApproverNode> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-1)).value;
		int roleleft = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).left;
		int roleright = ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()).right;
		String role = (String)((java_cup.runtime.Symbol) CUP$ProManParser$stack.peek()).value;
		
      ArrayList<ApproverNode> list = new ArrayList<>();
      list.add(new ApproverNode(name, role));
      RESULT = list;
    
              CUP$ProManParser$result = parser.getSymbolFactory().newSymbol("approver_list",19, ((java_cup.runtime.Symbol)CUP$ProManParser$stack.elementAt(CUP$ProManParser$top-2)), ((java_cup.runtime.Symbol)CUP$ProManParser$stack.peek()), RESULT);
            }
          return CUP$ProManParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ProManParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ProManParser$do_action(
    int                        CUP$ProManParser$act_num,
    java_cup.runtime.lr_parser CUP$ProManParser$parser,
    java.util.Stack            CUP$ProManParser$stack,
    int                        CUP$ProManParser$top)
    throws java.lang.Exception
    {
              return CUP$ProManParser$do_action_part00000000(
                               CUP$ProManParser$act_num,
                               CUP$ProManParser$parser,
                               CUP$ProManParser$stack,
                               CUP$ProManParser$top);
    }
}

