
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Nov 20 21:09:37 COT 2025
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int METADATA = 3;
  public static final int BUDGET = 11;
  public static final int MITIGATION = 35;
  public static final int COMMENTS = 41;
  public static final int CREATED_ON = 16;
  public static final int HIGH = 32;
  public static final int STATUS = 12;
  public static final int APPROVER = 43;
  public static final int OVERALL = 39;
  public static final int LEVEL = 31;
  public static final int GENERAL = 22;
  public static final int SPECIFIC = 23;
  public static final int PHASE = 26;
  public static final int RISK = 30;
  public static final int REQUIRED_BY = 42;
  public static final int COST = 38;
  public static final int SUMMARY = 21;
  public static final int VERSION = 15;
  public static final int CLIENT = 4;
  public static final int CODE = 14;
  public static final int CONTEXT = 5;
  public static final int TEAM = 9;
  public static final int SCHEDULE = 8;
  public static final int EOF = 0;
  public static final int LOW = 34;
  public static final int error = 1;
  public static final int PROJECT = 2;
  public static final int INCLUDE = 24;
  public static final int RISKS = 10;
  public static final int EMAIL = 20;
  public static final int NUMBER = 47;
  public static final int START = 27;
  public static final int NAME = 18;
  public static final int PREPARED_BY = 17;
  public static final int EXCLUDE = 25;
  public static final int OBJECTIVES = 6;
  public static final int LBRACE = 44;
  public static final int MEDIUM = 33;
  public static final int CONTACT = 19;
  public static final int RBRACE = 45;
  public static final int SCOPE = 7;
  public static final int CURRENCY = 36;
  public static final int END = 28;
  public static final int STRING = 46;
  public static final int ITEM = 37;
  public static final int APPROVALS = 13;
  public static final int HEALTH = 40;
  public static final int ROLE = 29;
}

